# Generated by Django 5.1.4 on 2025-01-20 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_fablabs', to=settings.AUTH_USER_MODEL, verbose_name='Administrateurs')),
                ('users', models.ManyToManyField(blank=True, related_name='fablabs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FabLab',
                'verbose_name_plural': 'FabLabs',
            },
        ),
    ]
