# Generated by Django 5.1.4 on 2025-01-20 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabusers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Photo de profil')),
                ('accepts_contact', models.BooleanField(default=False, verbose_name="Accepte d'être contacté")),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('fablab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabusers.fablab', verbose_name='FabLab principal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
