# Generated by Django 5.1.4 on 2025-01-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabusers', '0003_migrate_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name="Couleur de l'avatar"),
        ),
    ]
