# Generated by Django 5.1.4 on 2025-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabusers', '0006_fablab_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expanded_sections',
            field=models.JSONField(blank=True, default=dict, verbose_name='Sections déroulées'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_completed_tasks',
            field=models.BooleanField(default=True, verbose_name='Afficher les tâches complétées'),
        ),
    ]
