# Generated by Django 5.1.4 on 2025-01-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabprojects', '0002_taskfile'),
    ]

    operations = [
    ]
