# Generated by Django 5.1.4 on 2025-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabprojects', '0003_auto_20250122_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sections', to='fabprojects.tag'),
        ),
    ]
