# Generated by Django 5.1.4 on 2025-03-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabprojects', '0004_section_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='fabprojects.view'),
        ),
    ]
