# Generated by Django 5.1.4 on 2025-01-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabprojects', '0004_section_tags'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            DROP INDEX IF EXISTS fabprojects_task_view_id_71cbf4d0;
            ALTER TABLE fabprojects_task DROP COLUMN view_id;
            ''',
            reverse_sql='''
            ALTER TABLE fabprojects_task ADD COLUMN view_id INTEGER REFERENCES fabprojects_view(id);
            CREATE INDEX fabprojects_task_view_id_71cbf4d0 ON fabprojects_task(view_id);
            '''
        ),
    ]
