# Generated by Django 5.1.4 on 2025-01-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabprojects', '0005_task_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='view',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='fabprojects.view'),
        ),
        migrations.RunSQL(
            sql='UPDATE fabprojects_task SET view_id = (SELECT view_id FROM fabprojects_section WHERE fabprojects_section.id = fabprojects_task.section_id);',
            reverse_sql='UPDATE fabprojects_task SET view_id = NULL;'
        ),
        migrations.AlterField(
            model_name='task',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='fabprojects.view'),
        ),
    ] 