# Generated by Django 5.1.4 on 2025-04-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='allday',
            field=models.BooleanField(default=False, verbose_name='Événement sur toute la journée'),
        ),
    ]
