# Generated by Django 5.1.4 on 2025-05-07 08:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabmaintenance', '0008_merge_20250401_1547'),
        ('fabusers', '0007_userprofile_expanded_sections_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Durée estimée')),
                ('actual_duration', models.DurationField(blank=True, null=True, verbose_name='Durée réelle')),
                ('material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût matière')),
                ('energy_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût énergie')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût total')),
                ('co2_emission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Émission CO2 (kg)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis à jour le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabmaintenance.machine', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='job_files/', verbose_name='Fichier')),
                ('file_type', models.CharField(choices=[('design', 'Fichier de conception'), ('gcode', 'GCODE'), ('result', 'Résultat'), ('other', 'Autre')], max_length=20, verbose_name='Type de fichier')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='fabjobs.job', verbose_name='Job')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Fichier de job',
                'verbose_name_plural': 'Fichiers de jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramme'), ('m2', 'Mètre carré'), ('m', 'Mètre linéaire'), ('l', 'Litre')], max_length=2, verbose_name='Unité')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par unité')),
                ('co2_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CO2 par unité (kg)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis à jour le')),
                ('fablab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabusers.fablab', verbose_name='FabLab')),
                ('machine_types', models.ManyToManyField(to='fabmaintenance.machinetype', verbose_name='Types de machines compatibles')),
            ],
            options={
                'verbose_name': 'Matériau',
                'verbose_name_plural': 'Matériaux',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabjobs.material', verbose_name='Matériau'),
        ),
    ]
