# Generated by Django 5.1.4 on 2025-05-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabjobs', '0001_initial'),
        ('fabusers', '0007_userprofile_expanded_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='fablab',
        ),
        migrations.AddField(
            model_name='material',
            name='fablabs',
            field=models.ManyToManyField(to='fabusers.fablab', verbose_name='FabLabs'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('g', 'Grammes'), ('kg', 'Kilogrammes'), ('m', 'Mètres'), ('cm', 'Centimètres'), ('mm', 'Millimètres'), ('l', 'Litres'), ('ml', 'Millilitres'), ('pcs', 'Pièces')], max_length=3, verbose_name='Unité'),
        ),
    ]
