# Generated by Django 5.1.4 on 2025-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabjobs', '0002_remove_material_fablab_material_fablabs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(default='#808080', help_text='Code couleur hexadécimal (ex: #FF0000 pour rouge)', max_length=7, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
    ]
