# Generated by Django 5.1.4 on 2025-05-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabjobs', '0003_material_color_alter_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Rouge'), ('#FF4500', 'Orange Rouge'), ('#FFA500', 'Orange'), ('#FFD700', 'Or'), ('#FFFF00', 'Jaune'), ('#9ACD32', 'Jaune Vert'), ('#32CD32', 'Vert Lime'), ('#008000', 'Vert'), ('#20B2AA', 'Vert Clair'), ('#00FFFF', 'Cyan'), ('#1E90FF', 'Bleu Dodger'), ('#0000FF', 'Bleu'), ('#4B0082', 'Indigo'), ('#8A2BE2', 'Bleu Violet'), ('#9400D3', 'Violet'), ('#FF1493', 'Rose Vif'), ('#FF69B4', 'Rose'), ('#FFB6C1', 'Rose Clair'), ('#FFC0CB', 'Rose Pâle'), ('#FFE4E1', 'Rose Misty'), ('#A52A2A', 'Marron'), ('#8B4513', 'Marron Selle'), ('#D2691E', 'Marron Chocolat'), ('#CD853F', 'Marron Pérou'), ('#DEB887', 'Marron Clair'), ('#F5F5DC', 'Beige'), ('#FAEBD7', 'Blanc Antiquité'), ('#FFFAF0', 'Blanc Floral'), ('#F0F8FF', 'Bleu Alice'), ('#F5F5F5', 'Gris Blanc'), ('#E6E6FA', 'Lavande'), ('#FFF0F5', 'Lavande Rose'), ('#FFE4B5', 'Moka'), ('#FFDAB9', 'Pêche'), ('#E0FFFF', 'Cyan Clair'), ('#F0FFFF', 'Azur'), ('#F0FFF0', 'Miel'), ('#FFF0F5', 'Lavande Rose'), ('#FFE4E1', 'Rose Misty'), ('#E6E6FA', 'Lavande'), ('#D8BFD8', 'Violet Clair'), ('#DDA0DD', 'Prune'), ('#EE82EE', 'Violet'), ('#FF00FF', 'Magenta'), ('#BA55D3', 'Orchidée Moyen'), ('#9370DB', 'Violet Moyen'), ('#8A2BE2', 'Bleu Violet'), ('#9400D3', 'Violet'), ('#9932CC', 'Orchidée Sombre'), ('#8B008B', 'Magenta Sombre')], default='#808080', max_length=7, verbose_name='Couleur'),
        ),
    ]
