# Generated by Django 5.1.4 on 2025-05-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabjobs', '0004_alter_material_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(default='#808080', max_length=7, verbose_name='Couleur'),
        ),
    ]
