# Generated by Django 5.1.4 on 2025-01-20 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabusers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='machine_images/')),
                ('fablab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabusers.fablab')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabmaintenance.machinetype')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period_days', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabmaintenance.machinetype')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('scheduling_type', models.CharField(choices=[('today', "Aujourd'hui"), ('scheduled', 'Planifiée'), ('periodic', 'Périodique')], default='scheduled', max_length=10)),
                ('period_days', models.IntegerField(blank=True, null=True)),
                ('custom_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('significant', models.BooleanField(default=False, help_text='Indique si cette maintenance est marquante')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabmaintenance.machine')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabmaintenance.maintenancetype')),
            ],
        ),
    ]
