# Generated by Django 5.1.4 on 2025-03-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabmaintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricant')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('description', models.TextField(verbose_name='Description')),
                ('documentation_url', models.URLField(blank=True, verbose_name='URL de la documentation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='machine_templates/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabmaintenance.machinetype', verbose_name='Type de machine')),
            ],
            options={
                'verbose_name': 'Template de machine',
                'verbose_name_plural': 'Templates de machines',
                'ordering': ['manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('period_days', models.IntegerField(verbose_name='Périodicité (jours)')),
                ('estimated_duration', models.DurationField(verbose_name='Durée estimée')),
                ('priority', models.IntegerField(choices=[(1, 'Basse'), (2, 'Moyenne'), (3, 'Haute'), (4, 'Critique')], default=2, verbose_name='Priorité')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('required_tools', models.TextField(blank=True, verbose_name='Outils nécessaires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('machine_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_templates', to='fabmaintenance.machinetemplate', verbose_name='Template de machine')),
            ],
            options={
                'verbose_name': 'Template de maintenance',
                'verbose_name_plural': 'Templates de maintenance',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
