# Generated by Django 5.1.4 on 2025-03-25 10:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabmaintenance', '0002_machinetemplate_maintenancetemplate'),
        ('fabusers', '0006_fablab_invitation_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name'], 'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
        migrations.AlterModelOptions(
            name='machinetype',
            options={'ordering': ['name'], 'verbose_name': 'Type de machine', 'verbose_name_plural': 'Types de machines'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['scheduled_date'], 'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenances'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'ordering': ['name'], 'verbose_name': 'Type de maintenance', 'verbose_name_plural': 'Types de maintenance'},
        ),
        migrations.AddField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='machine',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabmaintenance.machinetemplate', verbose_name='Template utilisé'),
        ),
        migrations.AddField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis à jour le'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='color',
            field=models.CharField(default='#007bff', help_text='Code couleur hexadécimal (ex: #007bff)', max_length=7, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='default_maintenance_period',
            field=models.IntegerField(default=30, help_text='Nombre de jours par défaut entre les maintenances', verbose_name='Période de maintenance par défaut (jours)'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='icon',
            field=models.CharField(default='fas fa-cog', help_text="Classe CSS de l'icône Font Awesome (ex: fas fa-printer)", max_length=50, verbose_name='Icône Font Awesome'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='requires_certification',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisation de ce type de machine nécessite une certification", verbose_name='Nécessite une certification'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='safety_instructions',
            field=models.TextField(blank=True, help_text='Instructions de sécurité générales pour ce type de machine', null=True, verbose_name='Instructions de sécurité'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis à jour le'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis à jour le'),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='fablab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabusers.fablab', verbose_name='FabLab'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machine_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabmaintenance.machinetype', verbose_name='Type de machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de série'),
        ),
        migrations.AlterField(
            model_name='machinetemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='machinetemplate',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='fabmaintenance.machinetype', verbose_name='Type de machine'),
        ),
        migrations.AlterField(
            model_name='machinetemplate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Réalisée par'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réalisation'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='custom_type_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom personnalisé'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabmaintenance.machine', verbose_name='Machine'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabmaintenance.maintenancetype', verbose_name='Type de maintenance'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='period_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Périodicité (jours)'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='scheduled_date',
            field=models.DateTimeField(verbose_name='Date prévue'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='scheduling_type',
            field=models.CharField(choices=[('today', "Aujourd'hui"), ('scheduled', 'Planifiée'), ('periodic', 'Périodique')], default='scheduled', max_length=10, verbose_name='Type de programmation'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='significant',
            field=models.BooleanField(default=False, help_text='Indique si cette maintenance est marquante', verbose_name='Maintenance marquante'),
        ),
        migrations.AlterField(
            model_name='maintenancetemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='maintenancetemplate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Personnalisé'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabmaintenance.machinetype', verbose_name='Type de machine'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='period_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Périodicité (jours)'),
        ),
        migrations.CreateModel(
            name='DefaultMaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('period_days', models.IntegerField(verbose_name='Périodicité (jours)')),
                ('estimated_duration', models.DurationField(verbose_name='Durée estimée')),
                ('priority', models.IntegerField(choices=[(1, 'Basse'), (2, 'Moyenne'), (3, 'Haute'), (4, 'Critique')], default=2, verbose_name='Priorité')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('required_tools', models.TextField(blank=True, verbose_name='Outils nécessaires')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mis à jour le')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_maintenances', to='fabmaintenance.machinetype', verbose_name='Type de machine')),
            ],
            options={
                'verbose_name': 'Maintenance par défaut',
                'verbose_name_plural': 'Maintenances par défaut',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
