# Generated by Django 5.1.4 on 2025-03-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabmaintenance', '0004_maintenancetype_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmaintenancetype',
            name='period_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Périodicité (jours)'),
        ),
    ]
