# Generated by Django 5.1.4 on 2025-03-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabmaintenance', '0005_alter_defaultmaintenancetype_period_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetemplate',
            name='period_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Périodicité (jours)'),
        ),
    ]
