# Generated by Django 5.1.4 on 2025-03-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabmaintenance', '0006_alter_maintenancetemplate_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetype',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='required_tools',
            field=models.TextField(blank=True, null=True, verbose_name='Outils nécessaires'),
        ),
    ]
