# Generated by Django 5.1.4 on 2025-04-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabmaintenance', '0004_update_maintenance_fields'),
        ('fabmaintenance', '0007_maintenancetype_instructions_and_more'),
    ]

    operations = [
    ]
